import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { EnergyProvider } from "@/app/context/EnergyContext";
import { Toaster } from "@/components/ui/toaster";
import NavbarController from "@/components/NavbarController";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EnergyDrive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (


    
    <html lang="en">
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased`

        }
      >
        <EnergyProvider>
          
          <NavbarController/>
          {children}
          
          
        </EnergyProvider>
        <Toaster />
      </body>
    </html>
  );
}
